# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projekty/CVUT/Vivado2023.1/semestrak_rev/semestrak_rev.srcs/sources_1/ip/blk_mem_ROM/blk_mem_ROM.xci
# IP: The module: 'blk_mem_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projekty/CVUT/Vivado2023.1/semestrak_rev/semestrak_rev.gen/sources_1/ip/blk_mem_ROM/blk_mem_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/projekty/CVUT/Vivado2023.1/semestrak_rev/semestrak_rev.srcs/sources_1/ip/blk_mem_ROM/blk_mem_ROM.xci
# IP: The module: 'blk_mem_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projekty/CVUT/Vivado2023.1/semestrak_rev/semestrak_rev.gen/sources_1/ip/blk_mem_ROM/blk_mem_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
